PresentationLayer/Models/User/EditAccountModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PresentationLayer.Models.User
{
    public class EditAccountModel
    {
        [Required]
        [Display(Name = "Username")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "Full name")]
        public string Name { get; set; }

        public string Address { get; set; }

        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date of birth")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy}")]
        public DateTime? DateOfBirth { get; set; }
    }
}

PresentationLayer/Controllers/CustomerController.cs
using BussinesLayer.DTOs;
using BussinesLayer.Facades;
using DataAccessLayer.Enums;
using Microsoft.AspNet.Identity;
using PresentationLayer.Filters.Authorization;
using PresentationLayer.Models.Customer;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    [HandleError]
    [CustomAuthorize]
    public class CustomerController : Controller
    {
        private readonly UserFacade userFacade;
        private readonly CustomerFacade customerFacade;
        private readonly ProjectFacade projectFacade;

        public CustomerController(UserFacade userFacade, CustomerFacade customerFacade, ProjectFacade projectFacade)
        {
            this.userFacade = userFacade;
            this.customerFacade = customerFacade;
            this.projectFacade = projectFacade;
        }

        public ActionResult ViewAllCustomers()
        {
            var model = new ViewAllCustomersModel()
            {
                Customers = customerFacade.GetAllCustomers()
            };
            return View("ViewAllCustomers", model);
        }
        
        [CustomAuthorize(Roles = "Administrator,Employee")]
        public ActionResult GrantCustomerRights(int? userId)
        {
            if (!userId.HasValue)
                return View("BadInput");

            if (userFacade.IsUserCustomer(userId.Value))
                RedirectToAction("UserDetail", "User", new { userId = userId.Value });

            var user = userFacade.GetUserById(userId.Value);
            if (user == null)
                return View("BadInput");

            var model = new EditCustomerModel()
            {
                UserId = user.Id,
            };
            return View("GrantCustomerRights", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Administrator,Employee")]
        public ActionResult GrantCustomerRights(EditCustomerModel model)
        {
            if (model == null)
                return View("BadInput");

            if (!ModelState.IsValid)
                return View(model);

            if (userFacade.IsUserCustomer(model.UserId))
                RedirectToAction("UserDetail", "User", new { userId = model.UserId });

            customerFacade.CreateCustomer(new CustomerDTO() { Type = model.Type }, model.UserId);
            userFacade.AddCustomerRightsToUser(model.UserId);
            return RedirectToAction("UserDetail", "User", new { userId = model.UserId });
        }

        [CustomAuthorize(Roles = "Administrator,Employee")]
        public ActionResult RemoveCustomerRights(int? userId)
        {
            if (!userId.HasValue)
                return View("BadInput");

            if (!userFacade.IsUserCustomer(userId.Value))
                RedirectToAction("UserDetail", "User", new { userId = userId.Value });

            var customer = customerFacade.GetCustomerById(userId.Value);
            if (customer == null)
                return View("BadInput");

            customerFacade.DeleteCustomer(customer);
            userFacade.RemoveCustomerRightsFromUser(userId.Value);
            return RedirectToAction("UserDetail", "User", new { userId = userId.Value });
        }

        public ActionResult EditCustomer(int? userId)
        {
            if (!userId.HasValue)
                return View("BadInput");

            if (!User.IsInRole(UserRole.Administrator.ToString()) && (User.Identity.GetUserId<int>() != userId.Value))
                return View("AccessForbidden");

            var customer = customerFacade.GetCustomerById(userId.Value);
            if(customer == null)
                return View("BadInput");

            var model = new EditCustomerModel()
            {
                UserId = customer.Id,
                Type = customer.Type
            };
            return View("EditCustomer", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCustomer(EditCustomerModel model)
        {
            if (model == null)
                return View("BadInput");

            if (!ModelState.IsValid)
                return View(model);

            if (!User.IsInRole(UserRole.Administrator.ToString()) && (User.Identity.GetUserId<int>() != model.UserId))
                return View("AccessForbidden");

            var customer = customerFacade.GetCustomerById(model.UserId);
            if (customer == null)
                return View("BadInput");

            customer.Type = model.Type;

            customerFacade.UpdateCustomer(customer);
            return RedirectToAction("UserDetail", "User", new { userId = model.UserId });
        }
    }
}

PresentationLayer/Controllers/EmployeeController.cs
using BussinesLayer.DTOs;
using BussinesLayer.Facades;
using PresentationLayer.Filters.Authorization;
using PresentationLayer.Models.Employee;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    [HandleError]
    [CustomAuthorize]
    public class EmployeeController : Controller
    {
        private readonly UserFacade userFacade;
        private readonly EmployeeFacade employeeFacade;
        private readonly IssueFacade issueFacade;

        public EmployeeController(UserFacade userFacade, EmployeeFacade employeeFacade, IssueFacade issueFacade)
        {
            this.userFacade = userFacade;
            this.employeeFacade = employeeFacade;
            this.issueFacade = issueFacade;
        }

        public ActionResult ViewAllEmployees()
        {
            var model = new ViewAllEmployeesModel()
            {
                Employees = employeeFacade.GetAllEmployees()
            };
            return View("ViewAllEmployees", model);
        }
        
        [CustomAuthorize(Roles = "Administrator")]
        public ActionResult GrantEmployeeRights(int? userId)
        {
            if (!userId.HasValue)
                return View("BadInput");

            if(userFacade.GetUserById(userId.Value) == null)
                return View("BadInput");

            if (userFacade.IsUserEmployee(userId.Value))
                RedirectToAction("UserDetail", "User", new { userId = userId.Value });

            employeeFacade.CreateEmployee(new EmployeeDTO(), userId.Value);
            userFacade.AddEmployeeRightsToUser(userId.Value);
            return RedirectToAction("UserDetail", "User", new { userId = userId });
        }
        
        [CustomAuthorize(Roles = "Administrator")]
        public ActionResult RemoveEmployeeRights(int? userId)
        {
            if (!userId.HasValue)
                return View("BadInput");

            if (!userFacade.IsUserEmployee(userId.Value))
                RedirectToAction("UserDetail", "User", new { userId = userId.Value });

            var employee = employeeFacade.GetEmployeeById(userId.Value);
            if(employee == null)
                return View("BadInput");

            userFacade.RemoveEmployeeRightFromUser(userId.Value);
            employeeFacade.DeleteEmployee(employee);
            return RedirectToAction("UserDetail", "User", new { userId = userId.Value });
        }
    }
}

PresentationLayer/Controllers/UserController.cs
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using BussinesLayer.Facades;
using PresentationLayer.App_Start;
using PresentationLayer.Models.User;
using Microsoft.Owin.Security;
using BussinesLayer.DTOs;
using Microsoft.AspNet.Identity;
using PresentationLayer.Models.Issue;
using PresentationLayer.Models.Comment;
using PresentationLayer.Models.Employee;
using PresentationLayer.Models.Customer;
using PresentationLayer.Models.Project;
using PresentationLayer.Filters.Authorization;
using DataAccessLayer.Enums;
using System.Linq;

namespace PresentationLayer.Controllers
{
    [HandleError]
    [CustomAuthorize]
    public class UserController : Controller
    {
        private readonly UserFacade userFacade;
        private readonly EmployeeFacade employeeFacade;
        private readonly CustomerFacade customerFacade;
        private readonly ProjectFacade projectFacade;
        private readonly IssueFacade issueFacade;
        private readonly CommentFacade commentFacade;

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public UserController(
            UserFacade userFacade, EmployeeFacade employeeFacade, CustomerFacade customerFacade,
            ProjectFacade projectFacade, IssueFacade issueFacade, CommentFacade commentFacade)
        {
            this.userFacade = userFacade;
            this.employeeFacade = employeeFacade;
            this.customerFacade = customerFacade;
            this.projectFacade = projectFacade;
            this.issueFacade = issueFacade;
            this.commentFacade = commentFacade;
        }

        public UserController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            if (User.Identity.IsAuthenticated)
            {
                return Redirect("/");
            }

            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (model == null)
                return View("BadInput");

            if (!ModelState.IsValid)
                return View(model);

            var identity = userFacade.Login(model.Email, model.Password);
            if (identity == null)
            {
                ModelState.AddModelError("", "Bad E-Mail or Password");
                return View(model);
            }

            AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = false }, identity);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult ChangePassword()
        {
            var model = new ChangePasswordModel();
            return View("ChangePassword", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            if (model == null)
                return View("BadInput");

            if (!ModelState.IsValid)
                return View(model);

            var user = userFacade.GetUserById(User.Identity.GetUserId<int>());
            var identity = userFacade.Login(user.Email, model.CurrentPassword);
            if(identity == null)
            {
                ModelState.AddModelError("CurrentPassword", "Wrong password");
                return View(model);
            }
            userFacade.ChangePassword(user.Id, model.CurrentPassword, model.NewPassword);
            return RedirectToAction("UserDetail", new { userId = user.Id });
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            var model = new RegisterModel();
            return View("Register", model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterModel model)
        {
            if (model == null)
                return View("BadInput");

            if (!ModelState.IsValid)
                return View(model);

            var user = new UserDTO()
            {
                UserName = model.UserName,
                Name = model.Name,
                Email =  model.Email,
                Password = model.Password,
                Address = model.Address,
                PhoneNumber = model.PhoneNumber,
                DateOfBirth = model.DateOfBirth
            };

            /* Yes, this would also fail in facade. But it is harder to get nice message from there :) */
            if (!user.UserName.All(c => char.IsLetterOrDigit(c) && c < 128))
            {
                ModelState.AddModelError("UserName", "User Name can contain only alphanumeric symbols.");
                return View(model);
            }
            if(userFacade.GetUsersByUserName(user.UserName).Count > 0)
            {
                ModelState.AddModelError("UserName", "User Name is already taken.");
                return View(model);
            }
            if(userFacade.GetUsersByEmail(user.Email).Count > 0)
            {
                ModelState.AddModelError("Email", "E-Mail is already in use.");
                return View(model);
            }
            userFacade.Create(user);
            return RedirectToAction("Login");
        }

        public ActionResult ViewAllUsers()
        {
            var model = new ViewAllUsersModel()
            {
                Users = userFacade.GetAllUsers()
            };
            return View("ViewAllUsers", model);
        }

        public ActionResult UserDetail(int? userId)
        {
            if (!userId.HasValue)
                return View("BadInput");

            /* Get personal data */
            var user = userFacade.GetUserById(userId.Value);
            if(user == null)
                return View("BadInput");

            var model = new UserDetailModel()
            {
                User = user,
                ListIssuesModel = new ListIssuesModel()
                {
                    Issues = issueFacade.GetIssuesByCreator(user.Id)
                },
                ListCommentsModel = new ListCommentsModel()
                {
                    Comments = commentFacade.GetCommentsByAuthor(user.Id)
                }
            };
            /* Get employee data if any */
            var employee = employeeFacade.GetEmployeeById(user.Id);
            if (employee != null)
            {
                model.EmployeeDetailModel = new EmployeeDetailModel()
                {
                    Employee = employee,
                    ListIssuesModel = new ListIssuesModel()
                    {
                        Issues = issueFacade.GetIssuesByAssignedEmployee(user.Id)
                    }
                };
            }
            /* Get customer data if any */
            var customer = customerFacade.GetCustomerById(user.Id);
            if (customer != null)
            {
                model.CustomerDetailModel = new CustomerDetailModel()
                {
                    Customer = customer,
                    Projects = projectFacade.GetProjectsByCustomer(user.Id)
                        .Select(p => new ProjectOverviewModel()
                        {
                            ProjectId = p.Id,
                            ProjectName = p.Name,
                            CustomerId = p.Customer.Id,
                            CustomerName = p.Customer.User.Name,
                            ErrorCount = issueFacade.GetIssuesByProjectType(p.Id, IssueType.Error).Count,
                            RequirementCount = issueFacade.GetIssuesByProjectType(p.Id, IssueType.Requirement).Count
                        })
                        .ToList()
                };
            }
            model.IsDetailedUserAdmin = userFacade.IsUserAdmin(user.Id);
            model.IsAdmin = userFacade.IsUserAdmin(User.Identity.GetUserId<int>());
            model.IsEmployee = userFacade.IsUserEmployee(User.Identity.GetUserId<int>());
            model.CanModifyUser = model.IsAdmin || (user.Id == User.Identity.GetUserId<int>());
            model.CanChangePassword = user.Id == User.Identity.GetUserId<int>();

            return View("UserDetail", model);
        }
        
        public ActionResult Logout()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult EditUser(int? userId)
        {
            if (!userId.HasValue)
                return View("BadInput");

            if (!User.IsInRole(UserRole.Administrator.ToString()) && (User.Identity.GetUserId<int>() != userId))
                return View("AccessForbidden");

            var user = userFacade.GetUserById(userId.Value);
            if (user == null)
                return View("BadInput");

PresentationLayer/Views/User/ChangePassword.cshtml
@model PresentationLayer.Models.User.ChangePasswordModel
@{
    ViewBag.Title = "Change password";
}

<h2>Change account password</h2>
<hr />

@using(Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(m => m.CurrentPassword, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.CurrentPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CurrentPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.NewPassword, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.NewPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ConfirmNewPassword, new {@class = "col-md-2 control-label"})
            <div class="col-md-10">
                @Html.PasswordFor(m => m.ConfirmNewPassword, new {@class = "form-control"})
                @Html.ValidationMessageFor(m => m.ConfirmNewPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Change" />
            </div>
        </div>
    </div>    
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/User/EditAccount.cshtml
@model PresentationLayer.Models.User.EditAccountModel

@{
    ViewBag.Title = "Edit account";
}

<h2 style="text-align:left">
    Edit @Model.Name
</h2>
<hr />

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.DateOfBirth, new { htmlAttributes = new { @class = "datefield", @type = "date", @Value = String.Format("{0:yyyy-MM-dd}", Model.DateOfBirth)}})
            @Html.ValidationMessageFor(m => m.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save changes" class="btn btn-primary" />
        </div>
    </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/User/EditUser.cshtml
@model PresentationLayer.Models.User.EditUserModel

@{
    ViewBag.Title = "Edit user";
}

<h2 style="text-align:left">
    Edit user
</h2>
<hr />

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UserId)

    <div class="form-group">
        @Html.LabelFor(m => m.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.DateOfBirth, new { htmlAttributes = new { @class = "datefield", @type = "date", @Value = String.Format("{0:yyyy-MM-dd}", Model.DateOfBirth)}})
            @Html.ValidationMessageFor(m => m.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save changes" class="btn btn-primary" />
        </div>
    </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/User/UserDetail.cshtml
@model PresentationLayer.Models.User.UserDetailModel

@{
    ViewBag.Title = Model.User.UserName;
}

<h2 style="text-align:left">
    User @Model.User.UserName
    <span style="float:right">
        <div class="btn-toolbar">
            @if(Model.IsAdmin || Model.IsEmployee) {
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle">Manage privileges <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    @if(Model.IsAdmin) {
                        if(!Model.IsDetailedUserAdmin) {
                        <li>
                            @Html.ActionLink("Grant admin rights", "GrantAdministratorRights", "User", new { userId = Model.User.Id }, new { @class = "btn btn-link"} )
                        </li>
                        } else {
                        <li>
                            @Html.ActionLink("Revoke admin rights", "RemoveAdministratorRights", "User", new { userId = Model.User.Id }, new { @class = "btn btn-link"} )
                        </li>
                        }
                    }

                    @if(Model.IsAdmin) {
                        if(Model.EmployeeDetailModel == null) {
                        <li>
                            @Html.ActionLink("Grant employee rights", "GrantEmployeeRights", "Employee", new { userId = Model.User.Id }, new { @class = "btn btn-link"} )
                        </li>
                        } else {
                        <li>
                            @Html.ActionLink("Revoke employee rights", "RemoveEmployeeRights", "Employee", new { userId = Model.User.Id}, new { @class = "btn btn-link"})
                        </li>
                        }
                    }

                    @if(Model.IsAdmin || Model.IsEmployee) {
                        if(Model.CustomerDetailModel == null) {
                        <li>
                            @Html.ActionLink("Grant customer rights", "GrantCustomerRights", "Customer", new { userId = Model.User.Id }, new { @class = "btn btn-link"} )
                        </li>
                        } else {
                        <li>
                            @Html.ActionLink("Revoke customer rights", "RemoveCustomerRights", "Customer", new { userId = Model.User.Id}, new { @class = "btn btn-link"})
                        </li>
                        }
                    }
                </ul>
            </div>
            }

            @if(Model.CanChangePassword) {
                @Html.ActionLink("Change password", "ChangePassword", "User", new {}, new { @class = "btn btn-primary"})
            }

            @if(Model.CanModifyUser) {
                @Html.ActionLink("Edit user", "EditUser", "User", new { userId = Model.User.Id }, new { @class = "btn btn-primary"})
                @Html.ActionLink("Delete user", "DeleteUser", "User", new { userId = Model.User.Id }, new { @class = "btn btn-danger"})
            }

        </div>
    </span>
</h2>
<hr/>

<h4>Account information</h4>
<table class="table">
    <tr>
        <th>Id</th>
        <td>@Model.User.Id</td>
    </tr>
    <tr>
        <th>Username</th>
        <td>@Model.User.UserName</td>
    </tr>
    <tr>
        <th>Name</th>
        <td>@Model.User.Name</td>
    </tr>
    <tr>
        <th>E-Mail</th>
        <td>@Model.User.Email</td>
    </tr>
    <tr>
        <th>Date of birth</th>
        @if(Model.User.DateOfBirth == null) {
        <td>Unknown</td>
        } else {
        <td>@String.Format("{0:dd.MM.yyyy}", Model.User.DateOfBirth)</td>
        }
    </tr>
    <tr>
        <th>Address</th>
        @if(String.IsNullOrEmpty(Model.User.Address)) {
        <td>Unknown</td>
        } else {
        <td>@Model.User.Address</td>
        }
    </tr>
    <tr>
        <th>Phone</th>
        @if(String.IsNullOrEmpty(Model.User.PhoneNumber)) {
        <td>Unknown</td>
        } else {
        <td>@Model.User.PhoneNumber</td>
        }
    </tr>
</table>
<hr/>

<h4>
    Created issues 
    <a class="btn btn-default" data-toggle="collapse" data-target="#created-issues">Toggle</a>
</h4>
<div id="created-issues" class="collapse">
    @{ Html.RenderPartial("~/Views/Issue/ListIssues.cshtml", Model.ListIssuesModel); }
</div>
<hr/>

<h4>
    Posted comments 
    <a class="btn btn-default" data-toggle="collapse" data-target="#comments">Toggle</a>
</h4>
<div id="comments" class="collapse">
    @{ Html.RenderPartial("~/Views/Comment/ListComments.cshtml", Model.ListCommentsModel); }
</div>

@{
    if(Model.EmployeeDetailModel != null) {
    <hr />
    <h2 style="text-align:left">
        Employee
    </h2>
        Html.RenderPartial("~/Views/Employee/EmployeeDetail.cshtml", Model.EmployeeDetailModel);
    }
}

@{
    if(Model.CustomerDetailModel != null) {
    <hr/>
    <h2 style="text-align:left">
        Customer
        @if(Model.CanModifyUser) {
            <span style="float:right">
                @Html.ActionLink("Edit customer", "EditCustomer", "Customer", new { userId = Model.User.Id }, new { @class = "btn btn-primary"})
            </span>
        }
    </h2>
        Html.RenderPartial("~/Views/Customer/CustomerDetail.cshtml", Model.CustomerDetailModel);
    }
}

PresentationLayer/Views/User/ViewAllUsers.cshtml
@model PresentationLayer.Models.User.ViewAllUsersModel

@{
    ViewBag.Title = "Users";
}

<h2>Registered users</h2>

<table class="table">
    <tr>
        <th>User Name</th>
        <th>Full Name</th>
        <th>E-Mail</th>
        <th></th>
    </tr>

    @foreach (var user in Model.Users) {
        <tr>
            <td>@user.UserName</td>
            <td>@user.Name</td>
            <td>@user.Email</td>
            <td>@Html.ActionLink("Details", "UserDetail", "User", new { userId = user.Id }, new { @class = "btn btn-primary" })</td>
        </tr>
    }
</table>