PresentationLayer/Models/Issue/EditIssueModel.cs
using BussinesLayer.DTOs;
using DataAccessLayer.Enums;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace PresentationLayer.Models.Issue
{
    public class EditIssueModel
    {
        public int IssueId { get; set; }
        
        public int CreatorId { get; set; }
        
        public int ProjectId { get; set; }

        [Required]
        [MaxLength(256)]
        public string Title { get; set; }

        [MaxLength(4096)]
        public string Description { get; set; }

        [Required]
        [Range(1, 2)]
        public IssueType Type { get; set; }

        [Required]
        public int SelectedEmployeeId { get; set; }

        public List<EmployeeDTO> ExistingEmployees { get; set; }

        public IEnumerable<SelectListItem> EmployeeItems
        {
            get
            {
                var rval = ExistingEmployees
                    .Select(e => new SelectListItem
                    {
                        Value = e.Id.ToString(),
                        Text = e.User.Name + " (" + e.User.UserName + ")"
                    });
                return rval;
            }
        }
    }
}

PresentationLayer/Models/Issue/IssueDetailModel.cs
using BussinesLayer.DTOs;
using PresentationLayer.Models.Comment;
using System.ComponentModel.DataAnnotations;

namespace PresentationLayer.Models.Issue
{
    public class IssueDetailModel
    {
        public IssueDTO Issue { get; set; }

        public ListCommentsModel ListCommentsModel { get; set; }

        public bool IsUserSubscribed { get; set; }

        public bool CanChangeState { get; set; }

        public bool CanModify { get; set; }
    }
}

PresentationLayer/Models/Issue/ListIssuesModel.cs
using BussinesLayer.DTOs;
using System.Collections.Generic;

namespace PresentationLayer.Models.Issue
{
    public class ListIssuesModel
    {
        public List<IssueDTO> Issues { get; set; }

        public ListIssuesModel()
        {
            Issues = new List<IssueDTO>();
        }
    }
}

PresentationLayer/Models/Issue/ViewAllIssuesModel.cs
namespace PresentationLayer.Models.Issue
{
    public class ViewAllIssuesModel
    {
        public ListIssuesModel ListIssuesModel { get; set; }
    }
}

PresentationLayer/Controllers/CommentController.cs
using BussinesLayer.DTOs;
using BussinesLayer.Facades;
using Microsoft.AspNet.Identity;
using PresentationLayer.Filters.Authorization;
using PresentationLayer.Models.Comment;
using System;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    [HandleError]
    [CustomAuthorize]
    public class CommentController : Controller
    {
        private readonly CommentFacade commentFacade;
        private readonly IssueFacade issueFacade;

        public CommentController(CommentFacade commentFacade, IssueFacade issueFacade)
        {
            this.commentFacade = commentFacade;
            this.issueFacade = issueFacade;
        }

        public ActionResult PostComment(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            var issue = issueFacade.GetIssueById(issueId.Value);
            if (issue == null)
                return View("BadInput");

            var model = new PostCommentModel()
            {
                IssueId = issue.Id
            };

            return View("PostComment", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostComment(PostCommentModel model)
        {
            if (model == null)
                return View("BadInput");

            if (!ModelState.IsValid)
                return View(model);

            var comment = new CommentDTO()
            {
                Subject = model.Subject,
                Message = model.Message,
                Created = DateTime.Now
            };
            
            commentFacade.CreateComment(comment, model.IssueId, User.Identity.GetUserId<int>());
            return RedirectToAction("IssueDetail", "Issue", new { issueId = model.IssueId });
        }
    }
}

PresentationLayer/Controllers/IssueController.cs
using BussinesLayer.DTOs;
using BussinesLayer.Facades;
using DataAccessLayer.Enums;
using Microsoft.AspNet.Identity;
using PresentationLayer.Filters.Authorization;
using PresentationLayer.Models.Comment;
using PresentationLayer.Models.Issue;
using System;
using System.Data.Entity.Core;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    [HandleError]
    [CustomAuthorize]
    public class IssueController : Controller
    {
        private readonly IssueFacade issueFacade;
        private readonly CommentFacade commentFacade;
        private readonly ProjectFacade projectFacade;
        private readonly UserFacade userFacade;
        private readonly EmployeeFacade employeeFacade;
        private readonly NotificationFacade notificationFacade;

        public IssueController(
            IssueFacade issueFacade, 
            CommentFacade commentFacade, 
            ProjectFacade projectFacade,
            UserFacade userFacade,
            EmployeeFacade employeeFacade,
            NotificationFacade notificationFacade)
        {
            this.issueFacade = issueFacade;
            this.commentFacade = commentFacade;
            this.projectFacade = projectFacade;
            this.userFacade = userFacade;
            this.employeeFacade = employeeFacade;
            this.notificationFacade = notificationFacade;
        }

        public ActionResult ViewAllIssues()
        {
            var model = new ViewAllIssuesModel()
            {
                ListIssuesModel = new ListIssuesModel()
                {
                    Issues = issueFacade.GetAllIssues()
                }
            };
            return View("ViewAllIssues", model);
        }

        public ActionResult IssueDetail(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            var issue = issueFacade.GetIssueById(issueId.Value);
            if(issue == null)
                return View("BadInput");

            var model = new IssueDetailModel()
            {
                Issue = issue,
                ListCommentsModel = new ListCommentsModel()
                {
                    Comments = commentFacade.GetCommentsByIssue(issue.Id)
                }
            };
            int userId = User.Identity.GetUserId<int>();

            model.IsUserSubscribed = notificationFacade.IsUserSubbedToIssue(userId, issueId.Value);
            model.CanChangeState = User.IsInRole(UserRole.Administrator.ToString()) || 
                User.IsInRole(UserRole.Employee.ToString());
            model.CanModify = User.IsInRole(UserRole.Administrator.ToString()) || 
                (userId == issue.Creator.Id);

            return View("IssueDetail", model);
        }

        public ActionResult AddIssueToProject(int? projectId)
        {
            if (!projectId.HasValue)
                return View("BadInput");

            var model = new EditIssueModel()
            {
                ProjectId = projectId.Value,
                ExistingEmployees = employeeFacade.GetAllEmployees()
            };
            return View("AddIssueToProject", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddIssueToProject(EditIssueModel model)
        {
            if (model == null)
                return View("BadInput");

            if (!ModelState.IsValid)
            {
                model.ExistingEmployees = employeeFacade.GetAllEmployees();
                return View(model);
            }

            var issue = new IssueDTO()
            {
                Title = model.Title,
                Description = model.Description,
                Type = model.Type,
                Status = IssueStatus.New,
                Created = DateTime.Now
            };
            var notification = new NotificationDTO();

            var newId = issueFacade.CreateIssue(issue, model.ProjectId, User.Identity.GetUserId<int>(), model.SelectedEmployeeId);
            /* Subscribing creator and assigned employee */
            notificationFacade.CreateNotification(notification, newId, User.Identity.GetUserId<int>());
            /* To prevent double notification for single user and issue */
            if(User.Identity.GetUserId<int>() != model.SelectedEmployeeId)
                notificationFacade.CreateNotification(notification, newId, model.SelectedEmployeeId);

            return RedirectToAction("IssueDetail", new { issueId = newId });
        }

        public ActionResult EditIssue(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            var issue = issueFacade.GetIssueById(issueId.Value);
            if(issue == null)
                return View("BadInput");

            if (!User.IsInRole(UserRole.Administrator.ToString()) && (User.Identity.GetUserId<int>() != issue.Creator.Id))
                return View("AccessForbidden");

            var model = new EditIssueModel()
            {
                IssueId = issue.Id,
                CreatorId = issue.Creator.Id,
                ProjectId = issue.Project.Id,
                SelectedEmployeeId = issue.AssignedEmployee.Id,
                ExistingEmployees = employeeFacade.GetAllEmployees(),
                Title = issue.Title,
                Description = issue.Description,
                Type = issue.Type
            };
            return View("EditIssue", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditIssue(EditIssueModel model)
        {
            if (model == null)
                return View("BadInput");

            if (!ModelState.IsValid)
            {
                model.ExistingEmployees = employeeFacade.GetAllEmployees();
                return View(model);
            }

            if (!User.IsInRole(UserRole.Administrator.ToString()) && (User.Identity.GetUserId<int>() != model.CreatorId))
                return View("AccessForbidden");

            var issue = issueFacade.GetIssueById(model.IssueId);
            if(issue == null)
                return View("BadInput");

            issue.Title = model.Title;
            issue.Description = model.Description;
            issue.Type = model.Type;
            issueFacade.UpdateIssue(issue, model.SelectedEmployeeId, User.Identity.Name/*model.ProjectId, model.CreatorId, model.SelectedEmployeeId*/);
            return RedirectToAction("IssueDetail", new { issueId = model.IssueId });
        }

        public ActionResult DeleteIssue(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            var issue = issueFacade.GetIssueById(issueId.Value);
            if(issue == null)
                return View("BadInput");

            if (!User.IsInRole(UserRole.Administrator.ToString()) && (User.Identity.GetUserId<int>() != issue.Creator.Id))
                return View("AccessForbidden");

            issueFacade.DeleteIssue(issue);
            return RedirectToAction("ViewAllIssues");
        }

        [CustomAuthorize(Roles = "Administrator,Employee")]
        public ActionResult AcceptIssue(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            /*var issue = issueFacade.GetIssueById(issueId.Value);
            if(issue == null)
                return View("BadInput");

            issue.Status = IssueStatus.Accepted;
            issueFacade.UpdateIssue(issue, issue.Project.Id, issue.Creator.Id, issue.AssignedEmployee.Id);*/
            issueFacade.AcceptIssue(issueId.Value, User.Identity.Name);
            return RedirectToAction("IssueDetail", new { issueId = issueId });
        }

        [CustomAuthorize(Roles = "Administrator,Employee")]
        public ActionResult RejectIssue(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            /*var issue = issueFacade.GetIssueById(issueId.Value);
            if(issue == null)
                return View("BadInput");

            issue.Status = IssueStatus.Rejected;
            issue.Finished = DateTime.Now;
            issueFacade.UpdateIssue(issue, issue.Project.Id, issue.Creator.Id, issue.AssignedEmployee.Id);*/
            issueFacade.RejectIssue(issueId.Value, User.Identity.Name);
            return RedirectToAction("IssueDetail", new { issueId = issueId });
        }

        [CustomAuthorize(Roles = "Administrator,Employee")]
        public ActionResult CloseIssue(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            /*var issue = issueFacade.GetIssueById(issueId.Value);
            if(issue == null)
                return View("BadInput");

            issue.Status = IssueStatus.Closed;
            issue.Finished = DateTime.Now;
            issueFacade.UpdateIssue(issue, issue.Project.Id, issue.Creator.Id, issue.AssignedEmployee.Id);*/
            issueFacade.CloseIssue(issueId.Value, User.Identity.Name);
            return RedirectToAction("IssueDetail", new { issueId = issueId });
        }

        [CustomAuthorize(Roles = "Administrator,Employee")]
        public ActionResult ReopenIssue(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            /*var issue = issueFacade.GetIssueById(issueId.Value);
            if(issue == null)
                return View("BadInput");

            issue.Status = IssueStatus.Accepted;
            issue.Finished = null;
            issueFacade.UpdateIssue(issue, issue.Project.Id, issue.Creator.Id, issue.AssignedEmployee.Id);*/
            issueFacade.ReopenIssue(issueId.Value, User.Identity.Name);
            return RedirectToAction("IssueDetail", new { issueId = issueId });
        }
    }
}

PresentationLayer/Controllers/NotificationController.cs
using BussinesLayer.DTOs;
using BussinesLayer.Facades;
using Microsoft.AspNet.Identity;
using PresentationLayer.Filters.Authorization;
using PresentationLayer.Models.Notification;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    [HandleError]
    [CustomAuthorize]
    public class NotificationController : Controller
    {
        private readonly NotificationFacade notificationFacade;

        public NotificationController(NotificationFacade notificationFacade)
        {
            this.notificationFacade = notificationFacade;
        }

        public ActionResult SubscribeToIssue(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            int userId = User.Identity.GetUserId<int>();

            if (notificationFacade.IsUserSubbedToIssue(userId, issueId.Value))
                return RedirectToAction("IssueDetail", "Issue", new { issueId = issueId.Value });

            var notification = new NotificationDTO();

            notificationFacade.CreateNotification(notification, issueId.Value, userId);
            return RedirectToAction("IssueDetail", "Issue", new { issueId = issueId.Value });
        }

        public ActionResult UnsubscribeFromIssue(int? issueId)
        {
            if (!issueId.HasValue)
                return View("BadInput");

            int userId = User.Identity.GetUserId<int>();

            if (!notificationFacade.IsUserSubbedToIssue(userId, issueId.Value))
                return RedirectToAction("IssueDetail", "Issue", new { issueId = issueId.Value });

            var notification = notificationFacade.GetNotificationByIssueUser(issueId.Value, User.Identity.GetUserId<int>());
            if(notification != null)
                notificationFacade.DeleteNotification(notification);

            return RedirectToAction("IssueDetail", "Issue", new { issueId = issueId.Value });
        }

        public ActionResult ViewNotificationHistory()
        {
            int userId = User.Identity.GetUserId<int>();
            var model = new ViewNotificationHistoryModel()
            {
                ChangedIssues = notificationFacade.GetChangedIssuesByUser(userId),
            };
            return View("ViewNotificationHistory", model);
        }
    }
}

PresentationLayer/Views/Issue/AddIssueToProject.cshtml
@model PresentationLayer.Models.Issue.EditIssueModel
@{
    ViewBag.Title = "Create issue";
}

<h2>Create new issue</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ProjectId)

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", @rows = "5" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedEmployeeId, "Assign to employee", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedEmployeeId, Model.EmployeeItems, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectedEmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/Issue/EditIssue.cshtml
@model PresentationLayer.Models.Issue.EditIssueModel
@{
    ViewBag.Title = "Edit issue";
}

<h2>Edit issue</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.HiddenFor(model => model.IssueId)
    @Html.HiddenFor(model => model.ProjectId)
    @Html.HiddenFor(model => model.CreatorId)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", @rows = "5" })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, "Type of issue", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SelectedEmployeeId, "Assigned to", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.SelectedEmployeeId, Model.EmployeeItems, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SelectedEmployeeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save changes" class="btn btn-primary" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/Issue/IssueDetail.cshtml
@using DataAccessLayer.Enums
@model PresentationLayer.Models.Issue.IssueDetailModel

@{
    ViewBag.Title = Model.Issue.Title;
}

<h2 style="text-align:left">
    Issue
    @if(Model.IsUserSubscribed) {
        @Html.ActionLink("Unsubscribe", "UnsubscribeFromIssue", "Notification", new {issueId = Model.Issue.Id}, new {@class = "btn btn-info"})
    } else {
        @Html.ActionLink("Subscribe", "SubscribeToIssue", "Notification", new {issueId = Model.Issue.Id}, new {@class = "btn btn-info"})
    }
    <span style="float:right">
        <div class="btn-toolbar">
            @if(Model.CanChangeState) {
                if(Model.Issue.Status == IssueStatus.New) {
                    @Html.ActionLink("Accept", "AcceptIssue", "Issue", new {issueId = Model.Issue.Id}, new {@class = "btn btn-success"})
                    @Html.ActionLink("Reject", "RejectIssue", "Issue", new {issueId = Model.Issue.Id}, new {@class = "btn btn-warning"})
                } else if(Model.Issue.Status == IssueStatus.Accepted) {
                    @Html.ActionLink("Close", "CloseIssue", "Issue", new {issueId = Model.Issue.Id}, new {@class = "btn btn-info"})
                } else {
                    @Html.ActionLink("Reopen", "ReopenIssue", "Issue", new {issueId = Model.Issue.Id}, new {@class = "btn btn-default"})
                }
            }
            @if(Model.CanModify) {
                @Html.ActionLink("Edit issue", "EditIssue", "Issue", new {issueId = Model.Issue.Id}, new {@class = "btn btn-primary"})
                @Html.ActionLink("Delete issue", "DeleteIssue", "Issue", new {issueId = Model.Issue.Id}, new {@class = "btn btn-danger"})
            }
        </div>
    </span>
</h2>

<h4>General</h4>

<table class="table">
    <tr>
        <th>Id</th>
        <td>@Model.Issue.Id</td>
    </tr>
    <tr>
        <th>Title</th>
        <td>@Model.Issue.Title</td>
    </tr>
    <tr>
        <th>Description</th>
        @if(!String.IsNullOrEmpty(Model.Issue.Description)) {
            <td>@Model.Issue.Description</td>
        } else {
            <td></td>
        }
    </tr>
    <tr>
        <th>Issue type</th>
        <td>@Model.Issue.Type</td>
    </tr>
    <tr>
        <th>Issue status</th>
        <td>@Model.Issue.Status</td>
    </tr>
    <tr>
        <th>Time of creation</th>
        <td>@Model.Issue.Created</td>
    </tr>
    <tr>
        <th>Time of closure</th>
        @if(Model.Issue.Finished != null) {
            <td>@Model.Issue.Finished</td>
        } else {
            <td></td>
        }
    </tr>
    <tr>
        <th>Related to project</th>
        <td>@Html.ActionLink(Model.Issue.Project.Name, "ProjectDetail" , "Project", new {projectId = Model.Issue.Project.Id}, new {@class = "btn-link"})</td>
    </tr>
    <tr>
        <th>Assigned to</th>
        <td>@Html.ActionLink(Model.Issue.AssignedEmployee.User.Name, "UserDetail" , "User", new {userId = Model.Issue.AssignedEmployee.Id}, new {@class = "btn-link"})</td>
    </tr>
    <tr>
        <th>Created by</th>
        <td>@Html.ActionLink(Model.Issue.Creator.Name, "UserDetail" , "User", new { userId = Model.Issue.Creator.Id}, new {@class = "btn-link"})</td>
    </tr>
</table>

<h4>Discussion</h4>
@{ Html.RenderPartial("~/Views/Comment/DiscussionView.cshtml", Model.ListCommentsModel); }
<br/>
@Html.ActionLink("Comment!", "PostComment", "Comment", new { issueId = Model.Issue.Id }, new { @class = "btn btn-primary" })

PresentationLayer/Views/Issue/ListIssues.cshtml
@model PresentationLayer.Models.Issue.ListIssuesModel

@if(Model.Issues.Count != 0) {
<table class="table">
    <tr>
        <th>Title</th>
        <th>Project</th>
        <th>Author</th>
        <th>Assigned to</th>
        <th>Type</th>
        <th>Status</th>
        <th></th>
    </tr>

    @foreach (var issue in Model.Issues) {
    <tr>
        <td>@issue.Title</td>
        <td>@Html.ActionLink(issue.Project.Name, "ProjectDetail", "Project", new {projectId = issue.Project.Id}, new {@class = "btn-link"})</td>
        <td>@Html.ActionLink(issue.Creator.Name, "UserDetail", "User", new {userId = issue.Creator.Id}, new {@class = "btn-link"})</td>
        <td>@Html.ActionLink(issue.AssignedEmployee.User.Name, "UserDetail", "User", new { userId = issue.AssignedEmployee.Id}, new { @class = "btn-link"} )</td>
        <td>@issue.Type</td>
        <td>@issue.Status</td>
        <td>@Html.ActionLink("Detail", "IssueDetail", "Issue", new {issueId = issue.Id}, new {@class = "btn btn-primary"})</td>
    </tr>
    }

</table>
} else {
    <h5>No issues found.</h5>
}

PresentationLayer/Views/Issue/ViewAllIssues.cshtml
@model PresentationLayer.Models.Issue.ViewAllIssuesModel

@{
    ViewBag.Title = "Issues";
}

<h2>Issues</h2>

@{ Html.RenderPartial("~/Views/Issue/ListIssues.cshtml", Model.ListIssuesModel); }